blank_issues_enabled: true
contact_links:
  - name: Blank issue
    url: https://github.com/SWE-agent/SWE-agent/issues/new
    about: None of the above? Open a blank issue
  - name: Discord server
    url: https://discord.gg/AVEFbBn2rH
    about: Open ended discussion that is not suitable for a single issue.
